#!/usr/bin/ env bash
# terminates SSL on HAproxy

global                                                                                                                                    
        log /dev/log    local0                                                                                                            
        log /dev/log    local1 notice                                                                                                     
        chroot /var/lib/haproxy                                                                                                           
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners                                                     
        stats timeout 30s                                                                                                                 
        user haproxy                                                                                                                      
        group haproxy                                                                                                                     
        daemon                                                                                                                            
                                                                                                                                          
        # Default SSL material locations                        
        
defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

listen firstbalance
        bind *:80
        balance roundrobin
        option forwardfor
        option httpchk
        server 1813-web-01 34.138.159.69:80 check
        server 1813-web-02 35.227.86.94:80 check