#!/usr/bin/env bash
#printing Holberton School except for the 9th line 
n=1
while [ $n -le 10 ]
do
    echo "Holberton School"
    n=$(( n+1 ))
    if [[ "$n" == '10' ]]; then
	echo "Hi"
	continue
       
    fi
done
