#!/usr/bin/env bash
#counting to 20 with specifics for line 4,9 and 19
n=1
while [ $n -le 20 ]
do
    if [[ "$n" == '4' ]]; then
       echo "bad luck from China"
    elif [[ "$n" == '9' ]]; then
	echo "bad luck from Japan"
    elif [[ "$n" == '19' ]]; then
	echo "bad luck from Italy"
    else
	echo $n
    fi
    (( n++ ))
done
