#!/usr/bin/env bash
#counting to 20 with specifics for line 4,9 and 19
n=0
while [ $n -le 19 ]
do
    case $n in
	"4")echo "bad luck from China"
	    ;;
	"9")echo "bad luck from Japan"
	    ;;
	"17")echo "bad luck from Italy"
	    ;;
	*)
    esac
    (( n++ ))
    echo $n
done
